version: '{build}'
os: Visual Studio 2017
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
  SqlServer_ConnectionStringTemplate: Server=(local)\SQL2014;Database={0};User ID=sa;Password=Password12!
services:
  - mssql2014
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg