version: '{build}'
os: Visual Studio 2017 Preview
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg